apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bluesky-poster-data
  namespace: field-theories-bluesky-sync
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
