apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fave
  namespace: fave
spec:
  serviceName: fave
  replicas: 1
  selector:
    matchLabels:
      app: fave
  template:
    metadata:
      labels:
        app: fave
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: fave
        image: ghcr.io/t-eckert/fave:latest
        args:
        - "serve"
        - "--config"
        - "/app/config.json"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: FAVE_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fave-secret
              key: password
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /app/config.json
          subPath: config.json
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 2
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      volumes:
      - name: config
        configMap:
          name: fave-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path
      resources:
        requests:
          storage: 1Gi
