version: '3'

tasks:
  default:
    desc: List all tasks available.
    cmds:
     - task --list-all
    silent: true

  cluster:apply-namespaces:
    desc: Apply all namespace.yaml files in the repository.
    cmds:
      - |
        for file in $(find . -name "namespace.yaml"); do
          echo "Applying $file..."
          kubectl apply -f $file
        done
    silent: true

  db:access:
    desc: Open a psql instance against the Homelab Postgres database.
    cmds:
      - export PGPASSWORD=$(op read "op://Homelab/Homelab Postgres/password")
      - psql -h postgres-homelab -p 5432 -U postgres -d homelab
    silent: true

  workbench:ssh:
    desc: SSH into the workbench Debian instance.
    cmds:
      - TERM=xterm-256color ssh user@workbench.feist-gondola.ts.net
    silent: true

  workbench:mount:
    desc: Mount workbench code and data directories via SSHFS.
    cmds:
      - mkdir -p ~/mnt/workbench-code ~/mnt/workbench-data
      - sshfs user@workbench.feist-gondola.ts.net:/home/user/code ~/mnt/workbench-code
      - sshfs user@workbench.feist-gondola.ts.net:/home/user/data ~/mnt/workbench-data
    silent: false

  workbench:unmount:
    desc: Unmount workbench directories.
    cmds:
      - umount ~/mnt/workbench-code || true
      - umount ~/mnt/workbench-data || true
      - echo "Unmounted workbench directories"
    silent: false

  minecraft:status:
    desc: Check Minecraft server status.
    cmds:
      - echo "=== Minecraft Deployment Status ==="
      - kubectl get deployment minecraft -n minecraft
      - echo ""
      - echo "=== Minecraft Pods ==="
      - kubectl get pods -n minecraft
      - echo ""
      - echo "=== Minecraft Resource Usage ==="
      - kubectl top pod -n minecraft 2>/dev/null || echo "Metrics not available"
    silent: false

  minecraft:scale-down:
    desc: Scale down Minecraft server (saves 1Gi+ memory).
    cmds:
      - echo "Scaling down Minecraft server..."
      - "sed -i.bak 's/replicas: 1/replicas: 0/' cluster/minecraft/deployment.yaml"
      - rm cluster/minecraft/deployment.yaml.bak
      - echo "Updated deployment.yaml - replicas set to 0"
    silent: true

  minecraft:scale-up:
    desc: Scale up Minecraft server.
    cmds:
      - echo "Scaling up Minecraft server..."
      - "sed -i.bak 's/replicas: 0/replicas: 1/' cluster/minecraft/deployment.yaml"
      - rm cluster/minecraft/deployment.yaml.bak
      - echo "Updated deployment.yaml - replicas set to 1"
    silent: true
