apiVersion: batch/v1
kind: Job
metadata:
  name: atuin-db-init
  namespace: atuin
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: postgres-client
        image: postgres:16-alpine
        command:
        - sh
        - -c
        - |
          set -e
          export PGPASSWORD="$POSTGRES_PASSWORD"

          # Check if database exists
          DB_EXISTS=$(psql -h postgres.postgres -U postgres -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='atuin'")

          if [ "$DB_EXISTS" = "1" ]; then
            echo "Database 'atuin' already exists"
          else
            echo "Creating database 'atuin'..."
            psql -h postgres.postgres -U postgres -d postgres -c "CREATE DATABASE atuin;"
            echo "Database 'atuin' created successfully"
          fi
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-password
              key: password
      initContainers:
      - name: wait-for-postgres
        image: busybox:latest
        command:
        - sh
        - -c
        - |
          until nc -z postgres.postgres 5432; do
            echo "Waiting for postgres..."
            sleep 2
          done
          echo "Postgres is ready!"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-password
  namespace: atuin
type: Opaque
stringData:
  # Get the password from 1Password: op read "op://Homelab/Homelab Postgres/password"
  password: "REPLACE_WITH_PASSWORD"
