apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  imageRepositoryRef:
    name: uptime-kuma
  policy:
    semver:
      range: '>=2.0.0 <3.0.0'  # Track v2.x releases, avoid auto-upgrading to v3
