apiVersion: batch/v1
kind: CronJob
metadata:
  name: bluesky-poster
  namespace: bluesky-poster
spec:
  # Run every hour at minute 0
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: bluesky-poster
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: bluesky-poster
            image: ghcr.io/t-eckert/field-theories-bluesky-poster:latest
            imagePullPolicy: Always
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
            env:
            - name: RSS_FEED_URL
              value: "https://fieldtheories.blog/rss.xml"
            - name: BLUESKY_HANDLE
              valueFrom:
                secretKeyRef:
                  name: bluesky-poster-secret
                  key: handle
            - name: BLUESKY_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bluesky-poster-secret
                  key: password
            - name: DATABASE_PATH
              value: "/data/posted_items.db"
            - name: POST_AFTER_DATE
              value: "2025-11-24T00:00:00Z"  # TODO: Update to your desired cutoff date
            - name: RUST_LOG
              value: "info"
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "200m"
            volumeMounts:
            - name: data
              mountPath: /data
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: bluesky-poster-data
