apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyter-config
  namespace: workbench
data:
  jupyter_lab_config.py: |
    c.ServerApp.ip = '0.0.0.0'
    c.ServerApp.port = 8888
    c.ServerApp.token = ''
    c.ServerApp.password = ''
    c.ServerApp.allow_origin = '*'
    c.ServerApp.disable_check_xsrf = True
    c.ServerApp.allow_root = True
    c.ServerApp.notebook_dir = '/workspace'
    c.ServerApp.terminals_enabled = True
    c.LabApp.default_url = '/lab'
    
    # Git integration
    c.ServerApp.jpserver_extensions = {
        'jupyterlab_git': True
    }
