apiVersion: v1
kind: Service
metadata:
  name: jupyter-lab
  namespace: workbench
  labels:
    app: jupyter-lab
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
  selector:
    app: jupyter-lab
