apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workbench-notebooks
  namespace: workbench
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
