apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: field-theories
  namespace: field-theories
spec:
  imageRepositoryRef:
    name: field-theories
  filterTags:
    pattern: '^(20[0-9]{2})([0-9]{2})([0-9]{2})-[0-9]{4}-sha-[a-f0-9]+$'
    extract: '$1.$2.$3'
  policy:
    semver:
      range: '>=2025.0.0'
