apiVersion: v1
kind: Service
metadata:
  name: field-theories
  namespace: field-theories
spec:
  type: ClusterIP
  selector:
    app: field-theories
  ports:
  - name: http
    port: 80
    targetPort: 4321
    protocol: TCP
