apiVersion: v1
kind: Service
metadata:
  name: n8n-external
  namespace: n8n
  labels:
    app: n8n
    tailscale.com/proxy-class: "tailscale-proxy"
    tailscale.com/hostname: "n8n"
  annotations: {}
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - name: http
      port: 80
      targetPort: 5678
      protocol: TCP
  selector:
    app: n8n
