apiVersion: v1
kind: Service
metadata:
  name: bluesync
  namespace: field-theories
spec:
  type: ClusterIP
  selector:
    app: bluesync
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
