apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-db
  namespace: jellyfin
  labels:
    app.kubernetes.io/name: filebrowser
    app.kubernetes.io/instance: filebrowser
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
