apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-postgres-datasource
  namespace: monitoring
  labels:
    app: grafana
data:
  postgres-datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: PostgreSQL
      type: postgres
      access: proxy
      url: postgres.postgres.svc.cluster.local:5432
      database: homelab
      user: postgres
      secureJsonData:
        password: ${GF_POSTGRES_PASSWORD}
      jsonData:
        sslmode: disable
        postgresVersion: 1700
        timescaledb: false
      editable: true
