apiVersion: v1
kind: Service
metadata:
  name: grafana-external
  namespace: monitoring
  labels:
    app: grafana
    tailscale.com/proxy-class: "tailscale-proxy"
    tailscale.com/hostname: "grafana"
  annotations: {}
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
  - name: web
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: grafana
