apiVersion: v1
kind: Service
metadata:
  name: prometheus-external
  namespace: monitoring
  labels:
    app: prometheus
    tailscale.com/proxy-class: "tailscale-proxy"
    tailscale.com/hostname: "prometheus"
  annotations: {}
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
  - name: web
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: prometheus