apiVersion: v1
kind: Service
metadata:
  name: copyparty-external
  namespace: copyparty
  labels:
    app: copyparty
    tailscale.com/proxy-class: "tailscale-proxy"
    tailscale.com/hostname: "copyparty"
  annotations: {}
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - name: http
      port: 80
      targetPort: 3923
      protocol: TCP
  selector:
    app: copyparty