apiVersion: v1
kind: Service
metadata:
  name: copyparty
  namespace: copyparty
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3923
      protocol: TCP
      name: http
  selector:
    app: copyparty
